### ISSUE TITLE
Allow override of some services using dependencies inside the ContainerBuilder

### ISSUE THREAD

**Issue by carusogabriel** [chimeraphp/mapping#203]
Hello @lcobucci 👋🏼 

While upgrading a specific service of ours over @usabilla, we noticed something that we need your help with 😞 

First, the root cause of our problem: in `chimera/mapping:0.4`, there's something new: https://github.com/chimeraphp/mapping/blob/148a8170/src/Reader.php#L49-L55.
If we understood it, annotations over classes' methods will now have their annotations interpreted.

Now, our problem: we use one dependency that has a peculiar way to document their methods: https://github.com/async-aws/ses/blob/master/src/SesClient.php#L44. That causes us to see a message error in our tests while testing the migration to `chimera/mapping:0.4`:

```
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@region" in method AsyncAws\Ses\SesClient::sendEmail() was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

One possible solution: we could call `AnnotationReader`'s `addGlobalIgnoredName` (https://github.com/doctrine/annotations/blob/d13947c73/lib/Doctrine/Common/Annotations/AnnotationReader.php#L49-L57, but Chimera does not get that dependency from the `ContainerBuilder`: https://github.com/chimeraphp/mapping/blob/15624e580/src/Reader.php#L25.

Our question is: getting that `AnnotationReader` dependency from the `ContainerBuilder`, would that help us call its methods from our DI config files?

Thanks!

**Comment by lcobucci** [comment]
@carusogabriel the globally ignored names is a static property. You can add items to it **before** the container compilation and things should work.

Give it a try and let me know.

**Comment by carusogabriel** [comment]
@lcobucci It worked, thank you so much!
